server:
  port: 80
  servlet:
    context-path: /prd-wechat-admin-console/
spring:
  profiles:
    active: @profiles.active@

mybatis:
  # specify global profile location
  config-location: classpath:mybatis/mybatis-config.xml
  # specify mapping file location of sql
#  mapper-locations: classpath:mybatis/mapper/*.xml

#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql

